linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
    - bodyclose
    - errcheck
    - goimports
    - prealloc
    - tparallel

run:
  deadline: 2m
  # TODO: remove this once GHA is updated
  skip-dirs:
    - vendor

issues:
  exlude-dirs:
    - vendor
